# Generated by Django 5.0.3 on 2024-10-31 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_img",
                    models.ImageField(blank=True, null=True, upload_to="img/product"),
                ),
                ("product_description", models.TextField(blank=True)),
                (
                    "product_course_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_professor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("CLOTHING", "Clothing"),
                            ("BOOKS", "Books"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
