# Generated by Django 5.0.3 on 2024-10-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_course_number",
            new_name="course_number",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_img",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_professor",
            new_name="professor",
        ),
    ]
